name: soft_weather_tennis
version: "0.0.1"
publish_to: none

dependencies:
  another_flushbar: 1.12.29
  biometric_storage: ^4.1.3
  charts_flutter: ^0.12.0
  dio: ^4.0.4
  elementary: ^1.0.0
  encrypt: ^5.0.1
  firebase_crashlytics: ^2.5.0
  fl_chart: ^0.61.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^8.0.0
  flutter_state_notifier: ^0.7.3
  flutter_swiper_null_safety: ^1.0.2
  intl: ^0.17.0
  local_auth: ^2.1.6
  local_auth_android: ^1.0.21
  logger: ^1.1.0
  mask_text_input_formatter: ^2.4.0
  octo_image: ^1.0.2
  package_info_plus: ^3.0.3
  provider: ^6.0.2
  retrofit: ^3.3.1
  shared_preferences: ^2.0.20
  surf_logger: ^1.0.2


dev_dependencies:
  auto_route_generator: 5.0.3
  build_runner: 2.3.3
  dart_code_metrics: ^4.10.1
  flutter_dropdown: ^1.0.1+hotfix.1
  #  elementary_test: ^1.1.0
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^2.0.2
#  flutter_test:
#    sdk: flutter
  json_serializable: ^6.1.4
  surf_lint_rules: ^1.4.1
  retrofit_generator: 4.2.0
#  device_info_plus: 8.0.0



environment:
  sdk: ">=2.14.0-0 <3.0.0"

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
    - lib/features/pages/authorization_page/assets/images/
    - lib/features/pages/profile_page/assets/images/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/Nunito/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito/Nunito-Bold.ttf
          weight: 700
    - family: tennis_icons
      fonts:
        - asset: assets/fonts/tennis_icons.ttf

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/icons/icon_android.png"
  image_path_android: "assets/icons/icon_android.png"
  adaptive_icon_background: "assets/icons/background.png"

flutter_intl:
  enabled: false
  class_name: AppLocalizations
  main_locale: ru

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/splash_screen/splash_foreground.png
  fullscreen: true
