name: soft_weather_tennis
version: "0.0.1-dev.0"
publish_to: none

dependencies:
  dio: ^4.0.4
  elementary: ^1.0.0
  firebase_crashlytics: ^2.5.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  logger: ^1.1.0
  provider: ^6.0.2
  retrofit: ^3.0.1
  surf_logger: ^1.0.2

dev_dependencies:
  build_runner: ^2.1.7
  dart_code_metrics: ^4.10.1
#  elementary_test: ^1.1.0
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^2.0.2
#  flutter_test:
#    sdk: flutter
  json_serializable: ^6.1.4
  retrofit_generator: ^3.0.0
  surf_lint_rules: ^1.4.1

environment:
  sdk: ">=2.14.0-0 <3.0.0"

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/icons/icon_ios.png"
  image_path_android: "assets/icons/icon_android.png"
  adaptive_icon_background: "assets/icons/background.png"
  adaptive_icon_foreground: "assets/icons/foreground.png"

flutter_intl:
  enabled: false
  class_name: AppLocalizations
  main_locale: ru

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/splash_screen/splash_foreground.png
  fullscreen: true
